### ISSUE TITLE
[Global Sprint] Global Sprint Planning & ToDo's

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/mozilla_science_fellowship#13]
Global Sprint - Site Host Checklist     Status
## Initial Steps
- [x] Locate a space for the 2-day event.  The space should have ...  
  - good WiFi 
  - power outlets 
  - video screen (if possible)  
- [ ] Decide on any food you will offer - coffee, snacks, lunch ?  
## 4 Weeks Before the Sprint
- [x] Start to promote the event - email blasts, tweets, personal contacts, local meetup groups 
- [x] Finalize any space requirements - ie. WiFi login setup for participants, buiilding security access needs  
## 2 Weeks Before the Sprint
- [ ] Confirm any food requirements 
- [x] Setup Vidyo conferencing requirements - ie. download software, setup  account 
- [x] Plan A/V testing (if needed)  
- [ ] Setup communication channels - IRC, gitter chat etc.  
- [ ] Tweet about the event (include registration link) 
## 1 Weeks Before the Sprint
- [ ] Email Participants with directions to the location and any additional logistics requirements  
- [ ] Ask participants to complete the pre-sprint survey  
- [ ] Run through Vidyo Conferencing testing schedule with Science Lab contact (if needed)  
- [ ] Generate signs  
- [ ] Tweet about the event  (include registration link in still have spaces)  
## The Day Before
- [ ] Print off list of participants from registration site 
- [ ] Print signage - posters, Participation Guidelines, nametags  
- [ ] Test network access - confirm WiFi name and password  
- [ ] Check with food suppliers 
## The Morning of the Sprint
- [ ] Put up signage  
- [ ] Post network information  
- [ ] Greet Participants  
## First-day Welcome
- [ ] Make introductions  
- [ ] Mention the Participation Guidelines / Code of Conduct / Photo Release form (if needed)  
## During the Sprint
- [ ] Monitor refreshments  
## At the End of the Sprint
- [ ] Thank all participants for coming 
- [ ] Encourage participants to complete the post-sprint survey 
## Follow Up
- [ ] Create a blog post about the event at your site.
